<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <EmbeddedResource Include="Database\Scripts\*.sql" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>80f6863e-bdf6-4dda-8a8f-b38367f452c7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
  </ItemGroup>

</Project>
